# -*- coding: utf-8 -*-
"""Week 6 - Customer Churn Analysis System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBevaxpIS5_SO6dXaroXMpi6o7K_b81i
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

np.random.seed(0)

num_customer = 100000

data = {
    "Customer_ID": np.random.choice(np.arange(100000, 999999), size=num_customer, replace=False),
    "Age": np.random.randint(18,71, size=num_customer),
    "Gender": np.random.choice(["Male","Female"], size=num_customer),
    "Tenure": np.random.randint(1,11, size=num_customer),
    "Balance": np.random.randint(0,200000, size=num_customer),
    "Credict_Score": np.random.randint(300,901, size=num_customer),
    "Estimated_Salary": np.random.randint(10000,150000, size=num_customer),
    "Number_Of_Products": np.random.randint(1,5, size=num_customer),
    "isActiveMember": np.random.choice(["Yes","No"], size=num_customer),
    "Chrun": np.random.randint(0,2, size=num_customer)
}

df = pd.DataFrame(data)
df

print("Mean:\n")
print(df[["Balance", "Estimated_Salary", "Credict_Score"]].mean())

print("Median:\n")
print(df[["Balance", "Estimated_Salary", "Credict_Score"]].median())

print("Mode:\n")
print(df[["Balance", "Estimated_Salary", "Credict_Score"]].mode().iloc[0])

print("Standard Deviation:\n")
print(df[["Balance", "Estimated_Salary", "Credict_Score"]].std())

plt.figure(figsize=(15, 5))

values = ["Balance", "Estimated_Salary", "Credict_Score"]

for index, value in enumerate(values, 1):
    plt.subplot(1, 3, index)
    sns.histplot(df[value], kde=True, color='skyblue')
    plt.title(f'Distribution of {value}')

plt.tight_layout()
plt.show()

print("Churn Rate by Gender:")
print(df.groupby('Gender')['Chrun'].mean())
sns.barplot(x='Gender', y='Chrun', data=df, palette='magma')
plt.title('Churn Rate by Gender')
plt.show()

comparison = df.groupby('Chrun')[["Balance", "Estimated_Salary", "Credict_Score", "Age"]].mean()
print("Average Values by Churn Status:")
print(comparison)

plt.figure(figsize=(15, 5))

features_to_compare = ["Balance", "Age", "Credict_Score"]

for i, col in enumerate(features_to_compare, 1):
    plt.subplot(1, 3, i)
    sns.boxplot(x='Chrun', y=col, data=df, palette='Set2')
    plt.title(f'{col}: Churn vs Non-Churn')
    plt.xlabel('Stayed (0) vs Left (1)')

plt.tight_layout()
plt.show()

bins = [18, 30, 45, 60, 71]
labels = ['Young (18-30)', 'Middle-Aged (31-45)', 'Senior (46-60)', 'Elderly (60+)']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

age_churn = df.groupby('Age_Group')['Chrun'].mean()
print("Churn Rate by Age Group:")
print(age_churn)

plt.figure(figsize=(10, 6))
sns.barplot(x=age_churn.index, y=age_churn.values, palette='viridis')
plt.title('Churn Rate vs Age Group')
plt.ylabel('Churn Rate (Percentage)')
plt.show()

gender_churn = df.groupby('Gender')['Chrun'].mean()
print("Churn Rate by Gender:")
print(gender_churn)

plt.figure(figsize=(7, 5))
sns.barplot(x=gender_churn.index, y=gender_churn.values, palette='magma')
plt.title('Churn Rate: Male vs Female')
plt.ylabel('Churn Percentage')
plt.ylim(0, 1)
plt.show()

activity_churn = df.groupby('isActiveMember')['Chrun'].mean()
print("Churn Rate by Activity Status:")
print(activity_churn)

plt.figure(figsize=(7, 5))
sns.barplot(x=activity_churn.index, y=activity_churn.values, palette='viridis')
plt.title('Churn Rate: Active vs. Inactive Members')
plt.ylabel('Churn Percentage')
plt.axhline(df['Chrun'].mean(), color='red', linestyle='--', label='Average Churn')
plt.legend()
plt.show()

product_churn = df.groupby('Number_Of_Products')['Chrun'].mean()
print("Churn Rate by Number of Products:")
print(product_churn)

plt.figure(figsize=(8, 6))
sns.barplot(x=product_churn.index, y=product_churn.values, palette='rocket')
plt.title('Churn Rate by Number of Products Held')
plt.xlabel('Number of Products')
plt.ylabel('Churn Rate')
plt.axhline(df['Chrun'].mean(), color='blue', linestyle='--', label='Global Average')
plt.legend()
plt.show()

df['Age_Bins'] = pd.cut(df['Age'], bins=[18, 30, 45, 60, 71], labels=['Young', 'Middle-Aged', 'Senior', 'Elderly'])

plt.figure(figsize=(16, 12))

plt.subplot(2, 2, 1)
sns.barplot(x='Age_Bins', y='Chrun', data=df, palette='coolwarm')
plt.title('Churn Rate by Age Group')

plt.subplot(2, 2, 2)
sns.barplot(x='Gender', y='Chrun', data=df, palette='magma')
plt.title('Churn Rate by Gender')

plt.subplot(2, 2, 3)
sns.barplot(x='isActiveMember', y='Chrun', data=df, palette='viridis')
plt.title('Churn Rate: Active (Yes) vs Inactive (No)')

plt.subplot(2, 2, 4)
sns.barplot(x='Number_Of_Products', y='Chrun', data=df, palette='rocket')
plt.title('Churn Rate by Number of Products')

plt.tight_layout()
plt.show()

plt.figure(figsize=(18, 5))

plt.subplot(1, 3, 1)
sns.boxplot(x='Chrun', y='Balance', data=df, palette='Set2')
plt.title('Balance vs Churn')
plt.xlabel('Stayed (0) vs Left (1)')

plt.subplot(1, 3, 2)
sns.boxplot(x='Chrun', y='Credict_Score', data=df, palette='pastel')
plt.title('Credit Score vs Churn')
plt.xlabel('Stayed (0) vs Left (1)')

plt.subplot(1, 3, 3)
tenure_churn = df.groupby('Tenure')['Chrun'].mean()
sns.barplot(x=tenure_churn.index, y=tenure_churn.values, palette='magma')
plt.title('Churn Rate by Tenure')
plt.ylabel('Churn Rate')

plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 6))
df['Chrun'].value_counts().plot.pie(autopct='%1.1f%%', colors=['skyblue', 'lightcoral'], labels=['Stayed', 'Exited'])
plt.title('Overall Churn Proportion')
plt.ylabel('')
plt.show()

plt.figure(figsize=(8, 5))
sns.countplot(x='isActiveMember', hue='Chrun', data=df, palette='viridis')
plt.title('Count of Churn by Active Membership')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['Credict_Score'], bins=30, kde=True, color='purple')
plt.title('Distribution of Credit Scores')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Age', y='Balance', hue='Chrun', data=df.sample(1000), alpha=0.6)
plt.title('Age vs Balance (Colored by Churn)')
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(x='Chrun', y='Estimated_Salary', data=df, palette='Set3')
plt.title('Salary Distribution: Stayed (0) vs Left (1)')
plt.show()

plt.figure(figsize=(12, 8))
numeric_df = df.select_dtypes(include=['number'])
correlation = numeric_df.corr()

sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Feature Correlation Heatmap')
plt.show()